package com.whyy.snapnotes.logic

/**
 * 公式 raw(Unicode) → LaTeX 精确映射表。
 * AUTO-GENERATED from 手环端 _latex_table.js (scripts/gen_latex_table.gen.js) — 勿手改。
 * 与手环内置公式图 (gen_formulas.js) 使用同一份映射，保证渲染结果一致。
 */
internal val LATEX_TABLE: Map<String, String> = mapOf(
    "A∪B={x|x∈A或x∈B}" to "A \\cup B = \\{x \\mid x \\in A \\text{ 或 } x \\in B\\}",
    "A∩B={x|x∈A且x∈B}" to "A \\cap B = \\{x \\mid x \\in A \\text{ 且 } x \\in B\\}",
    "|A∪B|=|A|+|B|-|A∩B|" to "|A \\cup B| = |A| + |B| - |A \\cap B|",
    "f(-x)=-f(x)" to "f(-x) = -f(x)",
    "f(-x)=f(x)" to "f(-x) = f(x)",
    "f(x+T)=f(x)" to "f(x+T) = f(x)",
    "y=f(x+a)" to "y = f(x+a)",
    "a^m·a^n=a^(m+n)" to "a^m \\cdot a^n = a^{m+n}",
    "log_a(MN)=log_a M+log_a N" to "\\log_a (MN) = \\log_a M + \\log_a N",
    "log_a a^x=x" to "\\log_a a^x = x",
    "a^(log_a N)=N" to "a^{\\log_a N} = N",
    "x=-b/(2a)" to "x = -\\frac{b}{2a}",
    "Δ=b²-4ac" to "\\Delta = b^2 - 4ac",
    "x1+x2=-b/a" to "x_1 + x_2 = -\\frac{b}{a}",
    "x1·x2=c/a" to "x_1 \\cdot x_2 = \\frac{c}{a}",
    "(x^n)'=nx^(n-1)" to "(x^n)' = n x^{n-1}",
    "(sin x)'=cos x" to "(sin x)' = cos x",
    "(cos x)'=-sin x" to "(cos x)' = -sin x",
    "(e^x)'=e^x" to "(e^x)' = e^x",
    "(ln x)'=1/x" to "(\\ln x)' = \\frac{1}{x}",
    "(uv)'=u'v+uv'" to "(uv)' = u'v + uv'",
    "sin²+cos²=1" to "\\sin^2 x + \\cos^2 x = 1",
    "sin(A±B)=sinAcosB±cosAsinB" to "\\sin(A \\pm B) = \\sin A \\cos B \\pm \\cos A \\sin B",
    "cos2α=2cos²α-1" to "\\cos 2\\alpha = 2\\cos^2 \\alpha - 1",
    "sin2α=2sinαcosα" to "\\sin 2\\alpha = 2 \\sin \\alpha \\cos \\alpha",
    "y=Asin(ωx+φ)" to "y = A \\sin(\\omega x + \\varphi)",
    "T=2π/ω" to "T = \\frac{2\\pi}{\\omega}",
    "a·b=|a||b|cosθ" to "\\vec{a} \\cdot \\vec{b} = |\\vec{a}||\\vec{b}|\\cos\\theta",
    "a·b=x1x2+y1y2" to "\\vec{a} \\cdot \\vec{b} = x_1 x_2 + y_1 y_2",
    "|a|=√(x²+y²)" to "|\\vec{a}| = \\sqrt{x^2 + y^2}",
    "a∥b⇒x1y2=x2y1" to "\\vec{a} \\parallel \\vec{b} \\Rightarrow x_1 y_2 = x_2 y_1",
    "an=a1+(n-1)d" to "a_n = a_1 + (n-1)d",
    "Sn=n(a1+an)/2" to "S_n = \\frac{n(a_1 + a_n)}{2}",
    "an=a1·q^(n-1)" to "a_n = a_1 \\cdot q^{n-1}",
    "Sn=a1(1-q^n)/(1-q)" to "S_n = \\frac{a_1(1 - q^n)}{1 - q}",
    "a+b≥2√(ab)" to "a + b \\ge 2\\sqrt{ab}",
    "(a+b+c)/3≥³√(abc)" to "\\frac{a+b+c}{3} \\ge \\sqrt[3]{abc}",
    "(Σa_i²)(Σb_i²)≥(Σa_ib_i)²" to "(\\sum a_i^2)(\\sum b_i^2) \\ge (\\sum a_i b_i)^2",
    "d=|n·PA|/|n|" to "d = \\frac{|\\vec{n} \\cdot \\vec{PA}|}{|\\vec{n}|}",
    "V=1/3·Sh" to "V = \\frac{1}{3} S h",
    "cosθ=|n1·n2|/(|n1||n2|)" to "\\cos\\theta = \\frac{|\\vec{n_1} \\cdot \\vec{n_2}|}{|\\vec{n_1}||\\vec{n_2}|}",
    "d=|Ax0+By0+C|/√(A²+B²)" to "d = \\frac{|Ax_0 + By_0 + C|}{\\sqrt{A^2 + B^2}}",
    "x²/a²+y²/b²=1" to "\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1",
    "x²/a²-y²/b²=1" to "\\frac{x^2}{a^2} - \\frac{y^2}{b^2} = 1",
    "y²=2px" to "y^2 = 2px",
    "c²=a²-b²(椭圆)" to "c^2 = a^2 - b^2 \\quad \\text{(椭圆)}",
    "c²=a²+b²(双曲线)" to "c^2 = a^2 + b^2 \\quad \\text{(双曲线)}",
    "A_n^k=n!/(n-k)!" to "A_n^k = \\frac{n!}{(n-k)!}",
    "C_n^k=n!/[k!(n-k)!]" to "C_n^k = \\frac{n!}{k!(n-k)!}",
    "P(X=k)=C_n^k·p^k·(1-p)^(n-k)" to "P(X=k) = C_n^k \\cdot p^k \\cdot (1-p)^{n-k}",
    "E(X)=np" to "E(X) = np",
    "D(X)=np(1-p)" to "D(X) = np(1-p)",
    "v=v0+at" to "v = v_0 + at",
    "x=v0t+½at²" to "x = v_0 t + \\frac{1}{2} a t^2",
    "v²-v0²=2ax" to "v^2 - v_0^2 = 2ax",
    "v̄=(v0+v)/2" to "\\bar{v} = \\frac{v_0 + v}{2}",
    "h=½gt²" to "h = \\frac{1}{2} g t^2",
    "H=v0²/(2g)" to "H = \\frac{v_0^2}{2g}",
    "G=mg" to "G = mg",
    "F=kx" to "F = kx",
    "f=μN" to "f = \\mu N",
    "F=√(Fx²+Fy²)" to "F = \\sqrt{F_x^2 + F_y^2}",
    "F合=ma" to "F_\\text{合} = ma",
    "N=mg+ma(超重)" to "N = mg + ma \\quad \\text{(超重)}",
    "N=mg-ma(失重)" to "N = mg - ma \\quad \\text{(失重)}",
    "x=v0t" to "x = v_0 t",
    "y=½gt²" to "y = \\frac{1}{2} g t^2",
    "F向=mv²/r" to "F_\\text{向} = \\frac{m v^2}{r}",
    "F=Gm1m2/r²" to "F = \\frac{G m_1 m_2}{r^2}",
    "v=√(GM/r)" to "v = \\sqrt{\\frac{GM}{r}}",
    "T=2π√(r³/GM)" to "T = 2\\pi \\sqrt{\\frac{r^3}{GM}}",
    "W=Fscosθ" to "W = Fs \\cos\\theta",
    "P=Fv" to "P = Fv",
    "Ek=½mv²" to "E_k = \\frac{1}{2} m v^2",
    "Ep=mgh" to "E_p = mgh",
    "Ep=½kx²" to "E_p = \\frac{1}{2} k x^2",
    "W合=ΔEk" to "W_\\text{合} = \\Delta E_k",
    "p=mv" to "p = mv",
    "F·t=Δp" to "F \\cdot t = \\Delta p",
    "m1v1+m2v2=m1v1'+m2v2'" to "m_1 v_1 + m_2 v_2 = m_1 v_1' + m_2 v_2'",
    "v共=(m1v1+m2v2)/(m1+m2)" to "v_\\text{共} = \\frac{m_1 v_1 + m_2 v_2}{m_1 + m_2}",
    "F=kQq/r²" to "F = \\frac{kQq}{r^2}",
    "E=F/q" to "E = \\frac{F}{q}",
    "E=kQ/r²" to "E = \\frac{kQ}{r^2}",
    "E=U/d" to "E = \\frac{U}{d}",
    "U=Ed" to "U = Ed",
    "C=Q/U" to "C = \\frac{Q}{U}",
    "C=εS/(4πkd)" to "C = \\frac{\\varepsilon S}{4\\pi k d}",
    "I=Q/t" to "I = \\frac{Q}{t}",
    "I=U/R" to "I = \\frac{U}{R}",
    "R串=R1+R2" to "R_\\text{串} = R_1 + R_2",
    "1/R并=1/R1+1/R2" to "\\frac{1}{R_\\text{并}} = \\frac{1}{R_1} + \\frac{1}{R_2}",
    "P=UI=I²R" to "P = UI = I^2 R",
    "Q=I²Rt" to "Q = I^2 R t",
    "F=BILsinθ" to "F = BIL \\sin\\theta",
    "f=qvBsinθ" to "f = qvB \\sin\\theta",
    "qvB=mv²/r" to "qvB = \\frac{m v^2}{r}",
    "r=mv/(qB)" to "r = \\frac{mv}{qB}",
    "T=2πm/(qB)" to "T = \\frac{2\\pi m}{qB}",
    "Φ=BS" to "\\Phi = BS",
    "E=nΔΦ/Δt" to "E = n \\frac{\\Delta\\Phi}{\\Delta t}",
    "E=BLvsinθ" to "E = BLv \\sin\\theta",
    "E=L·ΔI/Δt" to "E = L \\frac{\\Delta I}{\\Delta t}",
    "e=Em sin(ωt)" to "e = E_m \\sin(\\omega t)",
    "Em=nBSω" to "E_m = nBS\\omega",
    "E=Em/√2" to "E = \\frac{E_m}{\\sqrt{2}}",
    "U1/U2=n1/n2" to "\\frac{U_1}{U_2} = \\frac{n_1}{n_2}",
    "P损=(P/U)²R" to "P_\\text{损} = \\left(\\frac{P}{U}\\right)^2 R",
    "F=-kx" to "F = -kx",
    "T=2π√(m/k)" to "T = 2\\pi \\sqrt{\\frac{m}{k}}",
    "T=2π√(L/g)" to "T = 2\\pi \\sqrt{\\frac{L}{g}}",
    "v=λf=λ/T" to "v = \\lambda f = \\frac{\\lambda}{T}",
    "n1sini1=n2sini2" to "n_1 \\sin i_1 = n_2 \\sin i_2",
    "n=c/v" to "n = \\frac{c}{v}",
    "sinC=1/n" to "\\sin C = \\frac{1}{n}",
    "Δx=Lλ/d" to "\\Delta x = \\frac{L\\lambda}{d}",
    "pV/T=C" to "\\frac{pV}{T} = C",
    "p1V1/T1=p2V2/T2" to "\\frac{p_1 V_1}{T_1} = \\frac{p_2 V_2}{T_2}",
    "ΔU=W+Q" to "\\Delta U = W + Q",
    "En=-13.6/n² eV" to "E_n = -\\frac{13.6}{n^2} \\text{ eV}",
    "ΔE=hf" to "\\Delta E = hf",
    "Ek=hν-W0" to "E_k = h\\nu - W_0",
    "ΔE=Δmc²" to "\\Delta E = \\Delta m c^2",
    "N=N0·(½)^(t/T)" to "N = N_0 \\cdot \\left(\\frac{1}{2}\\right)^{t/T}",
    "n=m/M" to "n = \\frac{m}{M}",
    "N=n·NA" to "N = n \\cdot N_A",
    "c=n/V" to "c = \\frac{n}{V}",
    "Vm=V/n=22.4L/mol(标况)" to "V_m = \\frac{V}{n} = 22.4 \\text{ L/mol}\\ \\text{(标况)}",
    "c浓·V浓=c稀·V稀" to "c_\\text{浓} \\cdot V_\\text{浓} = c_\\text{稀} \\cdot V_\\text{稀}",
    "n(Ox)×|Δv(Ox)| = n(Red)×|Δv(Red)|" to "n(\\text{Ox}) \\times |\\Delta v(\\text{Ox})| = n(\\text{Red}) \\times |\\Delta v(\\text{Red})|",
    "v=Δc/Δt" to "v = \\frac{\\Delta c}{\\Delta t}",
    "K=[C]^c[D]^d/([A]^a[B]^b)" to "K = \\frac{[\\text{C}]^c [\\text{D}]^d}{[\\text{A}]^a [\\text{B}]^b}",
    "α=已转化/起始×100%" to "\\alpha = \\frac{\\text{已转化}}{\\text{起始}} \\times 100\\%",
    "E池=E正-E负" to "E_\\text{池} = E_\\text{正} - E_\\text{负}",
    "Q=It=nF" to "Q = It = nF",
    "m=M·Q/(nF)" to "m = \\frac{M \\cdot Q}{nF}",
    "Kw=c(H⁺)·c(OH⁻)=10⁻¹⁴" to "K_w = c(\\text{H}^+) \\cdot c(\\text{OH}^-) = 10^{-14}",
    "pH=-lg[c(H⁺)]" to "pH = -\\lg[c(\\text{H}^+)]",
    "Ksp=[A⁺][B⁻]" to "K_{sp} = [\\text{A}^+][\\text{B}^-]",
    "pH=pKa+lg([A⁻]/[HA])" to "pH = pK_a + \\lg\\frac{[\\text{A}^-]}{[\\text{HA}]}",
    "ΔH=ΣE(反应物)-ΣE(生成物)" to "\\Delta H = \\sum E(\\text{反应物}) - \\sum E(\\text{生成物})",
    "ΔG=ΔH-TΔS" to "\\Delta G = \\Delta H - T\\Delta S",
    "ΔG<0自发" to "\\Delta G < 0 \\quad \\text{自发}",
    "ATP → ADP + Pi + 能量" to "ATP \\to ADP + P_i + \\text{能量}",
    "ADP + Pi + 能量 → ATP" to "ADP + P_i + \\text{能量} \\to ATP",
    "CO2 + C5 → 2C3" to "CO_2 + C_5 \\to 2C_3",
    "2C3 + [H] + ATP → (CH2O) + C5" to "2C_3 + [\\text{H}] + ATP \\to (CH_2O) + C_5",
    "6CO2 + 12H2O → C6H12O6 + 6O2 + 6H2O" to "6CO_2 + 12H_2O \\to C_6H_{12}O_6 + 6O_2 + 6H_2O",
    "C6H12O6+6O2→6CO2+6H2O+2870kJ" to "C_6H_{12}O_6 + 6O_2 \\to 6CO_2 + 6H_2O + 2870 \\text{ kJ}",
    "C6H12O6→2C3H6O3(乳酸)+少量ATP" to "C_6H_{12}O_6 \\to 2C_3H_6O_3\\ \\text{(乳酸)} + \\text{少量} ATP",
    "C6H12O6→2C2H5OH+2CO2+少量ATP" to "C_6H_{12}O_6 \\to 2C_2H_5OH + 2CO_2 + \\text{少量} ATP",
    "A-T, G-C" to "A\\text{-}T,\\ G\\text{-}C",
    "A-U, G-C" to "A\\text{-}U,\\ G\\text{-}C",
    "1密码子=3碱基=1氨基酸" to "1 \\text{密码子} = 3 \\text{碱基} = 1 \\text{氨基酸}",
    "64密码子=61编码+3终止" to "64 \\text{密码子} = 61 \\text{编码} + 3 \\text{终止}",
    "Aa × Aa → 1AA:2Aa:1aa" to "Aa \\times Aa \\to 1AA : 2Aa : 1aa",
    "3:1(完全显性)" to "3 : 1 \\quad \\text{(完全显性)}",
    "1:2:1(基因型)" to "1 : 2 : 1 \\quad \\text{(基因型)}",
    "AaBb × AaBb → 9:3:3:1" to "AaBb \\times AaBb \\to 9 : 3 : 3 : 1",
    "N=M×n/m" to "N = \\frac{M \\times n}{m}",
    "传递效率=下一营养级同化量/上一营养级同化量×100%" to "\\text{传递效率} = \\frac{\\text{下一营养级同化量}}{\\text{上一营养级同化量}} \\times 100\\%",
    "10%≤效率≤20%" to "10\\% \\le \\text{效率} \\le 20\\%",
    "H=90°-|φ-δ|" to "H = 90° - |\\varphi - \\delta|",
    "所求区时=已知区时±时区差" to "\\text{所求区时} = \\text{已知区时} \\pm \\text{时区差}",
    "t = t0 / sqrt(1 - v^2/c^2)" to "t = \\frac{t_0}{\\sqrt{1 - v^2/c^2}}",
    "L = L0 * sqrt(1 - v^2/c^2)" to "L = L_0 \\sqrt{1 - v^2/c^2}",
    "p = mv" to "p = mv",
    "I = Δp = Ft" to "I = \\Delta p = Ft",
)
